"""Shared execution logic for the Sea++ compiler GUI."""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from src.lexer import Lexer
from src.parser import Parser


PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIRECTORY = PROJECT_ROOT / "output"


@dataclass
class RunResult:
    """Results generated by one compiler execution."""

    phase: int
    base_name: str

    token_text: str = ""
    parser_text: str = ""

    generated_files: dict[str, Path] = field(
        default_factory=dict
    )

    warnings: list[str] = field(
        default_factory=list
    )


def safe_base_name(value: str) -> str:
    """Create a safe name for generated output files."""

    cleaned_name = re.sub(
        r"[^A-Za-z0-9_-]+",
        "_",
        value.strip(),
    )

    cleaned_name = cleaned_name.strip("_")

    return cleaned_name or "manual_input"


def write_text_file(
    path: Path,
    text: str,
) -> None:
    """Write UTF-8 text to a file."""

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    path.write_text(
        text + ("\n" if text else ""),
        encoding="utf-8",
    )


def analyze_source(
    source_code: str,
    base_name: str,
    phase: int,
) -> RunResult:
    """
    Run Phase 1 or Phase 2.

    Phase 1:
        Lexer only.

    Phase 2:
        Lexer, Parser, semantic checks,
        AST text, AST JSON, and graphical AST.
    """

    if phase not in {1, 2}:
        raise ValueError(
            "Phase must be either 1 or 2."
        )

    if not source_code.strip():
        raise ValueError(
            "The input source code is empty."
        )

    OUTPUT_DIRECTORY.mkdir(
        parents=True,
        exist_ok=True,
    )

    output_name = safe_base_name(
        base_name
    )

    result = RunResult(
        phase=phase,
        base_name=output_name,
    )

    # =========================================================
    # Phase 1: Lexer
    # =========================================================

    lexer = Lexer(source_code)
    tokens = lexer.tokenize()

    token_text = "\n".join(
        str(token)
        for token in tokens
    )

    result.token_text = token_text

    if phase == 1:
        token_output_path = (
            OUTPUT_DIRECTORY
            / f"{output_name}_phase1_tokens.txt"
        )
    else:
        token_output_path = (
            OUTPUT_DIRECTORY
            / f"{output_name}_tokens.txt"
        )

    write_text_file(
        token_output_path,
        token_text,
    )

    result.generated_files[
        "tokens"
    ] = token_output_path

    # In Phase 1, Parser and AST must not run.
    if phase == 1:
        return result

    # =========================================================
    # Phase 2: Parser and AST
    # =========================================================

    parser = Parser(tokens)

    parser_output_lines = parser.parse()

    if parser_output_lines is None:
        parser_output_lines = []

    parser_text = "\n".join(
        str(line)
        for line in parser_output_lines
    )

    result.parser_text = parser_text

    parser_output_path = (
        OUTPUT_DIRECTORY
        / f"{output_name}_parser_output.txt"
    )

    ast_json_path = (
        OUTPUT_DIRECTORY
        / f"{output_name}_ast.json"
    )

    ast_tree_path = (
        OUTPUT_DIRECTORY
        / f"{output_name}_ast_tree.txt"
    )

    ast_image_path = (
        OUTPUT_DIRECTORY
        / f"{output_name}_ast.png"
    )

    write_text_file(
        parser_output_path,
        parser_text,
    )

    result.generated_files[
        "parser_output"
    ] = parser_output_path

    # Save AST as JSON.
    parser.ast.save_json(
        ast_json_path
    )

    result.generated_files[
        "ast_json"
    ] = ast_json_path

    # Save readable AST tree.
    write_text_file(
        ast_tree_path,
        parser.ast.pretty(),
    )

    result.generated_files[
        "ast_tree"
    ] = ast_tree_path

    # Create graphical AST.
    try:
        image_path, dot_path = (
            parser.ast.render_graph(
                ast_image_path
            )
        )

        result.generated_files[
            "ast_image"
        ] = image_path

        result.generated_files[
            "ast_dot"
        ] = dot_path

    except (
        AttributeError,
        OSError,
        RuntimeError,
        ValueError,
    ) as error:
        result.warnings.append(
            "Phase 2 completed successfully, "
            "but the graphical AST could not be created: "
            f"{error}"
        )

    return result